/*You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.*/
class Solution {
    public char findTheDifference(String s, String t) {
        char res=0;
        int len = s.length();
        for(int i = 0; i < len; i++) {
            res^=(s.charAt(i)^t.charAt(i));
        }
        res^=t.charAt(len);
        return res;
    }
}
